Issue 416
ianfab/Fairy-Stockfish pull request #497
Opened 2022-06-14 14:58 UTC by johndoknjas

This pull request partly solves issue #416. The code now only allows certain special characters, depending on the variant being played. E.g., the "+" char won't be allowed in the seirawan variant. I've also called the FEN::validate_fen function from position.cpp - not sure if this would make sense or if it should be left as is. One thing I was a bit unsure of is whether '~' chars can appear in shogi FENs (and also whether they can appear in makpong FENs). Right now I'm assuming they're only allowed in shogi ones.

Some of the examples in issue 416 still aren't resolved. E.g., Kyotoshogi: p+nks+l/5/5/5/+LS+K+NP[-] w 0 1 is still treated as valid, since it contains no special chars which aren't allowed. It's just that some chars are in the wrong spots in the string.

2022-06-14 18:00 UTC, ianfab requested changes
Thanks for your PR. Overall it looks quite good, there are just two points I have in my CR comments. One is regarding the FEN validation in the position setup, the other is about the association of the allowed characters with the rules. I assume that the issues with failing tests will already be fixed when my comments are addressed, since the failures look related to them.

2022-06-15 02:42 UTC, johndoknjas commented
@ianfab Thanks for the feedback, it's very helpful. I'll work on implementing these changes.

2022-06-15 10:50 UTC, ianfab commented
There is one remaining test failure https://github.com/ianfab/Fairy-Stockfish/runs/6897885928?check_suite_focus=true I didn't expect. I think that is because the `conclude()` is only called on insert of variants, but the start FEN validation for custom variants already happens on parsing. So I think we need to call it also before https://github.com/ianfab/Fairy-Stockfish/blob/8ec72eff3bcf82648396756d03085d2c9363257d/src/parser.cpp#L399 or more generally at the beginning of the consistency checks there, as these might use derived properties in general. That is more of a bug in the current master, but didn't show before since we did not use derived properties there yet.

2022-06-15 11:25 UTC, ianfab commented
https://github.com/ianfab/Fairy-Stockfish/blob/8ec72eff3bcf82648396756d03085d2c9363257d/src/variant.cpp#L1560-L1569 is the related code. Custom variants are added, but the validation currently already happens directly after (as part of) parsing. It could be considered in the future to change the this, but for now the duplicate call of conclude to me is the simplest solution.

2022-06-15 11:40 UTC, johndoknjas commented
@ianfab Ah ok, I see.

2022-06-15 17:45 UTC, merged